#! /bin/sh
#
# Script for deploying generated bundle
#
# Author: Kaiwen Xu <kevin@kevxu.net>
#
# Usage: cb-repo-deploy rev|latest
#

# Load and validate configurations
. `dirname $0`/config.sh
. `dirname $0`/config-test.sh
test_config_ssh
test_config_remote
test_config_root
test_config_repo
test_config_admin_user
test_config_init_script

# Load dependencies
. `dirname $0`/lib/ssh.sh
. `dirname $0`/lib/admin.sh

set -e

usage() {
    echo >&2 "Usage: $ME rev|latest"
    exit 3
}

# Check argument
[ -z "$1" ] && usage

case "$1" in
    latest)
        # If argument is "latest", search for latest rev
        rev=$(cb_ssh_verbose "ls" "-t" "$CB_REPO" | sed -n 1p)
        ;;
    *)
        rev="$1"
        ;;
esac

cb_ssh "[ ! -d '$CB_REPO/$rev' ]" && { echo >&2 "$ME: Rev $rev not found"; exit 2; }

# Check already deployed version
if cb_ssh "[ -L '$CB_REPO_DEPLOYED' ]"; then
    deployed_path=$(cb_ssh_verbose "readlink" "$CB_REPO_DEPLOYED")
    if [ "$deployed_path" == "$CB_REPO/$rev" ]; then
        echo "$rev already deployed, abort"
        exit 1
    fi
fi

# Deploy
cb_ssh "rm" "$CB_REPO_DEPLOYED"
cb_ssh "ln" "-s" "$CB_REPO/$rev" "$CB_REPO_DEPLOYED"

# Restart server
cb_admin_restart_server

if [ $? -eq 0 ]; then
    echo "Successfully deployed $rev"
    exit 0
fi
