#! /bin/sh
#
# Script for list all available generated bundles
#
# Author: Kaiwen Xu <kevin@kevxu.net>
#
# Usage: cb-repo-list [dist|qa]
#

# Load configurations
. `dirname $0`/config.sh

# Load dependencies
. `dirname $0`/lib/ssh.sh

usage() {
	echo >&2 "Usage: $ME [dist|qa]"
    exit 3
}

# Check argument
[ -z "$1" ] && usage

set -e

case "$1" in
	dist)
		REPO_LINK="$CB_REPO_DEPLOY"
		STATUS="deployed"
		;;
	qa)
		REPO_LINK="$CB_REPO_TEST"
		STATUS="testing"
		CB_REMOTE="$CB_REMOTE_TEST"
		;;
	*)
		usage
		;;
esac

FORMAT="%m%m %Cred%H%Creset%nThe author was %Cgreen%an%Creset, created %Cgreen%ad%Creset (%Cgreen%ar%Creset)%nCommit message: %Cblue%s%Creset%n"
DATE_FORMAT="local"
SHOW_LOG="GIT_DIR='$CB_GIT_REPO' git show --format='$FORMAT' --date='$DATE_FORMAT' -s"

avail_repos=$(cb_ssh_verbose "ls" "-t" "$CB_REPO")
deployed_repo=$(basename `cb_ssh_verbose "readlink" "$REPO_LINK"`)

# Add deployed tag to the output message
cb_ssh_verbose "$SHOW_LOG" $avail_repos | sed -e "s/$deployed_repo/($STATUS) $deployed_repo/"
