#! /bin/sh
#
# Script for deploying generated bundle
#
# Author: Kaiwen Xu <kevin@kevxu.net>
#
# Usage: cb-repo-link [dist|qa] [rev|latest]
#

# Load configurations
. `dirname $0`/config.sh

# Load dependencies
. `dirname $0`/lib/ssh.sh
. `dirname $0`/lib/admin.sh

usage() {
    echo >&2 "Usage: $ME [dist|qa] [rev|latest]"
    exit 3
}

# Check argument
[ -z "$1" ] || [ -z "$2" ] && usage

set -e

case "$1" in
    dist)
        REPO_LINK="$CB_REPO_DEPLOY"
        START_SERVER="cb_admin_start_server"
        STOP_SERVER="cb_admin_stop_server"
        ;;
    qa)
        CB_REMOTE="$CB_REMOTE_TEST"
        REPO_LINK="$CB_REPO_TEST"
        START_SERVER="cb_admin_start_test_server"
        STOP_SERVER="cb_admin_stop_test_server"
        ;;
    *)
        usage
        ;;
esac

case "$2" in
    latest)
        # If argument is "latest", search for latest rev
        rev=$(cb_ssh_verbose "ls" "-t" "$CB_REPO" | sed -n 1p)
        ;;
    *)
        rev="$2"
        ;;
esac

cb_ssh "[ ! -d '$CB_REPO/$rev' ]" && { echo >&2 "$ME: Rev $rev not found"; exit 2; }

# Check already deployed version
if cb_ssh "[ -L '$REPO_LINK' ]"; then
    deployed_path=$(cb_ssh_verbose "readlink" "$REPO_LINK")
    if [ "$deployed_path" == "$CB_REPO/$rev" ]; then
        echo "$rev already deployed, abort"
        exit 1
    fi
fi

# Stop server
"$STOP_SERVER"

# Deploy
cb_ssh "rm" "-f" "$REPO_LINK"
cb_ssh "ln" "-s" "$CB_REPO/$rev" "$REPO_LINK"

# Restart server
"$START_SERVER"

if [ $? -eq 0 ]; then
    echo "Successfully deployed $rev"
    exit 0
fi
