#! /bin/sh
#
# Script for deploying generated bundle
#
# Author: Kaiwen Xu <kevin@kevxu.net>
#
# Usage: cb-repo-link deploy|test rev|latest
#

# Load and validate configurations
. `dirname $0`/config.sh
. `dirname $0`/config-test.sh
test_config_ssh
test_config_remote
test_config_root
test_config_repo
test_config_admin_user
test_config_init_script
test_config_init_script_test

# Load dependencies
. `dirname $0`/lib/ssh.sh
. `dirname $0`/lib/admin.sh

set -e

usage() {
    echo >&2 "Usage: $ME deploy|test rev|latest"
    exit 3
}

# Check argument
[ -z "$1" ] || [ -z "$2" ] && usage

case "$1" in
    deploy)
        REPO_LINK="$CB_REPO_DEPLOYED"
        RESTART_SERVER="cb_admin_restart_server"
        ;;
    test)
        REPO_LINK="$CB_REPO_TESTING"
        RESTART_SERVER="cb_admin_restart_test_server"
        ;;
    *)
        usage
        ;;
esac

case "$2" in
    latest)
        # If argument is "latest", search for latest rev
        rev=$(cb_ssh_verbose "ls" "-t" "$CB_REPO" | sed -n 1p)
        ;;
    *)
        rev="$1"
        ;;
esac

cb_ssh "[ ! -d '$CB_REPO/$rev' ]" && { echo >&2 "$ME: Rev $rev not found"; exit 2; }

# Check already deployed version
if cb_ssh "[ -L '$REPO_LINK' ]"; then
    deployed_path=$(cb_ssh_verbose "readlink" "$REPO_LINK")
    if [ "$deployed_path" == "$CB_REPO/$rev" ]; then
        echo "$rev already deployed, abort"
        exit 1
    fi
fi

# Deploy
cb_ssh "rm" "-f" "$REPO_LINK"
cb_ssh "ln" "-s" "$CB_REPO/$rev" "$REPO_LINK"

# Restart server
"$RESTART_SERVER"

if [ $? -eq 0 ]; then
    echo "Successfully deployed $rev"
    exit 0
fi
