#! /bin/sh
#
# Script for updating codebounty server side settings.json
#
# Author: Kaiwen Xu <kevin@kevxu.net>
#
# Usage: cb-settings-update file
#

usage() {
    echo >&2 "Usage: $ME [deploy|test] [file]"
    exit 3
}

# Check argument
[ -z "$1" ] || [ -z "$2" ] && usage

# Load configurations
. `dirname $0`/config.sh

# Load dependencies
. `dirname $0`/lib/ssh.sh
. `dirname $0`/lib/admin.sh
. `dirname $0`/lib/file.sh

set -e

SETTINGS_DEPLOY_FILE="settings.json"
SETTINGS_TEST_FILE="settings-test.json"

case "$1" in
    deploy)
        SETTINGS_FILE="$SETTINGS_DEPLOY_FILE"
        RESTART_SERVER="cb_admin_restart_server"
        ;;
    test)
        CB_REMOTE="$CB_REMOTE_TEST"
        SETTINGS_FILE="$SETTINGS_TEST_FILE"
        RESTART_SERVER="cb_admin_restart_test_server"
        ;;
    *)
        usage
        ;;
esac

[ ! -f "$2" ] && { echo >&2 "$ME: $2 not found"; exit 2; }

SETTINGS_PATH="$CB_ROOT/$SETTINGS_FILE"
SETTINGS_PERMISSION="0600"

# Upload settings file
if $VERBOSE; then echo "Uploading $2 to $SETTINGS_PATH on server..."; fi
cb_scp_upload "$2" "$SETTINGS_PATH"

if $VERBOSE; then echo "Changing ownership and permission of $SETTINGS_PATH..."; fi
cb_admin_ssh "sudo" "chown" "$CB_USER:$CB_GROUP" "$SETTINGS_PATH"    # Ensure setting file ownership
cb_ssh "chmod" "$SETTINGS_PERMISSION" "$SETTINGS_PATH"

if $VERBOSE; then echo "Verifying file integrity..."; fi
cb_verify_file "$2" "$SETTINGS_PATH"

# Restart server
"$RESTART_SERVER"

if [ $? -eq 0 ]; then
    echo "Successfully updated settings with $2"
    exit 0
fi
